name: Stock Downtrend Alerts

on:
  schedule:
    # Run weekdays at ~13:15 UTC (morning in America/Toronto; adjust as you like)
    - cron: "15 13 * * 1-5"
  workflow_dispatch: {}

jobs:
  run-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alerts
        env:
          # Comma-separated tickers (or use tickers.txt in the repo)
          TICKERS: ${{ vars.TICKERS }}
          # Email settings (store as GitHub Secrets)
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_TO:   ${{ vars.EMAIL_TO }}
        run: |
          python alert_downtrends.py

