name: Stock Downtrend Alerts

on:
  push:
    branches: [ "main" ]        # change if your default branch differs
  workflow_dispatch: {}
  schedule:
    - cron: "15 13 * * 1-5"     # weekdays 13:15 UTC

jobs:
  run-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alerts
        env:
          TICKERS:    ${{ vars.TICKERS }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_TO:   ${{ vars.EMAIL_TO }}
          SMTP_USER:  ${{ secrets.SMTP_USER }}
          SMTP_PASS:  ${{ secrets.SMTP_PASS }}
        run: |
          python alert_downtrends.py
